name: 'python tests'

# TODO: use the wheels from build-wheels

on:
  - 'push'
  - 'pull_request'

jobs:
  build-wheels:
    uses: habnabit/passacre/.github/workflows/build-wheels.yml@nearly-1.0

  linux:
    runs-on: 'ubuntu-latest'
    needs: ['build-wheels']
    strategy:
      matrix:
        python-version:
          - 'pypy3.9'
          - 'pypy3.10'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - run: 'echo ${{ needs.build-wheels }}'
      - uses: 'actions/checkout@v4'
      - name: 'set up python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'install tox'
        run: |
          python -mpip install -U pip setuptools
          python -mpip install -U tox tox-gh-actions
      - name: 'run tests'
        run: |
          tox
      - name: 'locate testing base'
        id: 'toxbase'
        run: |
          >>"$GITHUB_OUTPUT" {
            echo 'TOXBASE<<EOF'
            tox exec -q -- python3 -c 'import passacre, pathlib; print(pathlib.Path(passacre.__file__).parent.parent)'
            echo 'EOF'
          }
      - run: 'echo ${{ steps.toxbase.outputs.TOXBASE }}'
      - uses: 'coverallsapp/github-action@v2.3.4'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          path-to-lcov: 'lcov.info'

  macos:
    runs-on: ${{ matrix.runner }}
    needs: ['build-wheels']
    strategy:
      matrix:
        runner:
          - macos-12
          - macos-14
        python-version:
          - 'pypy3.9'
          - 'pypy3.10'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - run: 'echo ${{ needs.build-wheels }}'
      - uses: actions/checkout@v4
      - name: 'set up python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'install tox'
        run: |
          python -mpip install -U pip setuptools
          python -mpip install -U tox tox-gh-actions
      - name: 'run tests'
        run: |
          tox
      - uses: 'coverallsapp/github-action@v2.3.4'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          path-to-lcov: 'lcov.info'

  windows:
    runs-on: 'windows-latest'
    needs: ['build-wheels']
    strategy:
      matrix:
        python-version:
          - 'pypy3.9'
          - 'pypy3.10'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - run: 'echo ${{ needs.build-wheels }}'
      - uses: actions/checkout@v4
      - name: 'set up python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'install tox'
        run: |
          python -mpip install -U pip setuptools
          python -mpip install -U tox tox-gh-actions
      - name: 'run tests'
        run: |
          tox
      - uses: 'coverallsapp/github-action@v2.3.4'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          path-to-lcov: 'lcov.info'
